/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;
import Entity.Dosage;
import Entity.FonctionMetier;
import Entity.Medicament;
import Entity.Famille;
import Model.ModelMedicament;
import static java.lang.Float.parseFloat;
import javax.swing.JOptionPane;

/**
 *
 * @author fello
 */
public class frmAjoutMedicament extends javax.swing.JFrame {
    FonctionMetier fm;
    ModelMedicament mdlMedicament;

    /**
     * Creates new form frmAjoutMedicament
     */
    public frmAjoutMedicament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomMed = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        cboFamille = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEnregistre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContreIn = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEffets = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCompo = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Composition");

        jLabel2.setText("Nom du Medicament");

        jLabel3.setText("Prix échantillion");

        jLabel4.setText("Effets Medicaments  ");

        jLabel5.setText("Famille Medicament");

        jLabel6.setText("Contre indication");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Ajouter un Médicament");

        btnEnregistre.setBackground(new java.awt.Color(0, 0, 0));
        btnEnregistre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEnregistre.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistre.setText("Enregistré");
        btnEnregistre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnEnregistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnregistreMouseClicked(evt);
            }
        });

        txtContreIn.setColumns(20);
        txtContreIn.setLineWrap(true);
        txtContreIn.setRows(5);
        jScrollPane1.setViewportView(txtContreIn);

        txtEffets.setColumns(20);
        txtEffets.setLineWrap(true);
        txtEffets.setRows(5);
        jScrollPane2.setViewportView(txtEffets);

        txtCompo.setColumns(20);
        txtCompo.setLineWrap(true);
        txtCompo.setRows(5);
        jScrollPane3.setViewportView(txtCompo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomMed)
                                    .addComponent(txtPrix)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomMed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addComponent(btnEnregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnregistreMouseClicked
        // TODO add your handling code here:
        if(txtCompo.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Veuillez saisir une Composition svp svp "); 
        }
        else if(txtNomMed.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Veuillez saisir un Nom svp "); 
        }
        else if(txtPrix.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Veuillez saisir un Prix svp "); 
        }
        else if(txtEffets.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Veuillez saisir un effet svp "); 
        }
        else if(txtContreIn.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this, "Veuillez saisir une contre indication svp "); 
        }
        else
        {
            
            //c'est un objet et pour retourner un string .toString()
//            fm.InsererUnePrescription(cbxMed.getSelectedItem().toString(),cbxIndiv.getSelectedItem().toString(),cbxDosage.getSelectedItem().toString(),txtPosologie.getText());
              fm.InsererUnMedicament(txtCompo.getText(),txtNomMed.getText(),parseFloat(txtPrix.getText()),txtEffets.getText(),cboFamille.getSelectedItem().toString(),txtContreIn.getText());              
              mdlMedicament = new ModelMedicament();
              mdlMedicament.loadDatas6Colonnes(fm.getAllMedicaments());
              
            
            //on affiche un message de validation 
            
            JOptionPane.showMessageDialog(this, "Votre Médicament a bien été enregistré ");
            frmListerMedicament frm = new frmListerMedicament();
            
            frm.setVisible(true);
            
//                    frmAjt.setVisible(false);
           
            
        }
        
    }//GEN-LAST:event_btnEnregistreMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
         ConnexionBDD cnx = new ConnexionBDD();
             fm = new FonctionMetier();
             
             for(Famille f : fm.getAllNomFamille())
             {
                cboFamille.addItem(f.getLIBELLE());
                 
             }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAjoutMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAjoutMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAjoutMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAjoutMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAjoutMedicament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistre;
    private javax.swing.JComboBox<String> cboFamille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtCompo;
    private javax.swing.JTextArea txtContreIn;
    private javax.swing.JTextArea txtEffets;
    private javax.swing.JTextField txtNomMed;
    private javax.swing.JTextField txtPrix;
    // End of variables declaration//GEN-END:variables
}
