/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;
import Vues.frmMenuChoix;
import Entity.Individu;
import Entity.FonctionMetier;
import Model.ModelIndividu;
import javax.swing.JOptionPane;

/**
 *
 * @author natha
 */
public class frmListeTypeIndividus extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frmListeTypeIndividus
     */
    
    FonctionMetier fm;
    ModelIndividu mdlIndividu;
 
    public frmListeTypeIndividus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIndividus = new javax.swing.JTable();
        btnInsererIndividu = new javax.swing.JButton();
        btnModifierIndividu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLabelleInserer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Type Individus");

        tblIndividus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Libelle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIndividus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIndividusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIndividus);

        btnInsererIndividu.setBackground(new java.awt.Color(0, 0, 0));
        btnInsererIndividu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInsererIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnInsererIndividu.setText("Inserer un individu");
        btnInsererIndividu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnInsererIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererIndividuMouseClicked(evt);
            }
        });
        btnInsererIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsererIndividuActionPerformed(evt);
            }
        });

        btnModifierIndividu.setBackground(new java.awt.Color(0, 0, 0));
        btnModifierIndividu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModifierIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnModifierIndividu.setText("Modifier un individu");
        btnModifierIndividu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnModifierIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierIndividuMouseClicked(evt);
            }
        });
        btnModifierIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierIndividuActionPerformed(evt);
            }
        });

        jLabel2.setText("Libelle :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Modifier");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ajouter");

        jLabel5.setText("Libelle :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLibelle))
                            .addComponent(btnModifierIndividu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtLabelleInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnInsererIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addComponent(btnModifierIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLabelleInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(47, 47, 47)
                        .addComponent(btnInsererIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsererIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsererIndividuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsererIndividuActionPerformed

    private void btnInsererIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererIndividuMouseClicked
        // TODO add your handling code here:
//        ConnexionBDD bdd = new ConnexionBDD(); 
        fm = new FonctionMetier();
        
         if(txtLabelleInserer.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this,"Saisir un libelle ","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            fm.InsererIndividu(txtLabelleInserer.getText());
           //mdlIndividu = new ModelIndividu();
            
            JOptionPane.showMessageDialog(this,"Type d'individu ajouter avec succes","Validation",JOptionPane.PLAIN_MESSAGE);
            
             
        mdlIndividu = new ModelIndividu();
        mdlIndividu.loadDatas(fm.GetAllIndividus());
        tblIndividus.setModel(mdlIndividu);
        }
         
    }//GEN-LAST:event_btnInsererIndividuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        ConnexionBDD bdd = new ConnexionBDD(); 
        fm = new FonctionMetier();
        mdlIndividu = new ModelIndividu();
        mdlIndividu.loadDatas(fm.GetAllIndividus());
        tblIndividus.setModel(mdlIndividu);
        
       
    }//GEN-LAST:event_formWindowOpened

    private void btnModifierIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierIndividuMouseClicked
        // TODO add your handling code here:
        
        if(tblIndividus.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"Sélectionner un type d'individu","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            fm.modifierIndividu(txtLibelle.getText(), Integer.parseInt(tblIndividus.getValueAt(tblIndividus.getSelectedRow(), 0).toString()));
            mdlIndividu = new ModelIndividu();
            mdlIndividu.loadDatas(fm.GetAllIndividus());
            tblIndividus.setModel(mdlIndividu);
        }
        
       
    }//GEN-LAST:event_btnModifierIndividuMouseClicked

    private void btnModifierIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierIndividuActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnModifierIndividuActionPerformed

    private void tblIndividusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIndividusMouseClicked
        // TODO add your handling code here:
        
        txtLibelle.setText(tblIndividus.getValueAt(tblIndividus.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tblIndividusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListeTypeIndividus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListeTypeIndividus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsererIndividu;
    private javax.swing.JButton btnModifierIndividu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIndividus;
    private javax.swing.JTextField txtLabelleInserer;
    private javax.swing.JTextField txtLibelle;
    // End of variables declaration//GEN-END:variables
}
