/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

/**
 *
 * @author fello
 */
public class frmMenuChoix extends javax.swing.JFrame {

    /**
     * Creates new form frmMenueChoix
     */
    public frmMenuChoix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInteraction = new javax.swing.JButton();
        btnDeconnexion = new javax.swing.JButton();
        btnMedicament = new javax.swing.JButton();
        btnPrescrire = new javax.swing.JButton();
        btnStat = new javax.swing.JButton();
        btnIndividu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInteraction.setBackground(new java.awt.Color(0, 0, 0));
        btnInteraction.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnInteraction.setForeground(new java.awt.Color(255, 255, 255));
        btnInteraction.setText("Interaction");
        btnInteraction.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnInteraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInteractionMouseClicked(evt);
            }
        });
        btnInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteractionActionPerformed(evt);
            }
        });

        btnDeconnexion.setBackground(new java.awt.Color(0, 0, 0));
        btnDeconnexion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDeconnexion.setForeground(new java.awt.Color(255, 255, 255));
        btnDeconnexion.setText("Déconnexion");
        btnDeconnexion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeconnexionMouseClicked(evt);
            }
        });

        btnMedicament.setBackground(new java.awt.Color(0, 0, 0));
        btnMedicament.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMedicament.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicament.setText("Médicaments");
        btnMedicament.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnMedicament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicamentMouseClicked(evt);
            }
        });
        btnMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentActionPerformed(evt);
            }
        });

        btnPrescrire.setBackground(new java.awt.Color(0, 0, 0));
        btnPrescrire.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPrescrire.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescrire.setText("Prescrire");
        btnPrescrire.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnPrescrire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrescrireMouseClicked(evt);
            }
        });

        btnStat.setBackground(new java.awt.Color(0, 0, 0));
        btnStat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnStat.setForeground(new java.awt.Color(255, 255, 255));
        btnStat.setText("Statistiques");
        btnStat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnStat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatMouseClicked(evt);
            }
        });
        btnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatActionPerformed(evt);
            }
        });

        btnIndividu.setBackground(new java.awt.Color(0, 0, 0));
        btnIndividu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnIndividu.setForeground(new java.awt.Color(255, 255, 255));
        btnIndividu.setText("Individus");
        btnIndividu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        btnIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIndividuMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Menu : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnStat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrescrire, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnInteraction, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInteraction, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrescrire, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInteractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInteractionMouseClicked
        // TODO add your handling code here:
        frmInteraction1 frm = new frmInteraction1();
                    frm.setVisible(true);
        
        
    }//GEN-LAST:event_btnInteractionMouseClicked

    private void btnDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeconnexionMouseClicked
        // TODO add your handling code here:
        frmConnexion connexion = new frmConnexion();
        connexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeconnexionMouseClicked

    private void btnMedicamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicamentMouseClicked
        // TODO add your handling code here:
        frmListerMedicament frm = new frmListerMedicament();
                    frm.setVisible(true);
    }//GEN-LAST:event_btnMedicamentMouseClicked

    private void btnPrescrireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrescrireMouseClicked
            frmPrescription frm = new frmPrescription();
                    frm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrescrireMouseClicked

    private void btnStatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatMouseClicked

    private void btnIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIndividuMouseClicked
        // TODO add your handling code here:
         frmListeTypeIndividus frm = new frmListeTypeIndividus();
                    frm.setVisible(true);
    }//GEN-LAST:event_btnIndividuMouseClicked

    private void btnMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedicamentActionPerformed

    private void btnInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteractionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInteractionActionPerformed

    private void btnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatActionPerformed

        frmStat frm = new frmStat();
            
            frm.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuChoix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnIndividu;
    private javax.swing.JButton btnInteraction;
    private javax.swing.JButton btnMedicament;
    private javax.swing.JButton btnPrescrire;
    private javax.swing.JButton btnStat;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
