/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;
import Entity.FonctionMetier;
import Entity.Graph1;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author fello
 */
public class frmStat extends javax.swing.JFrame {

    
    ConnexionBDD cnx;
    FonctionMetier fm;
    /**
     * Creates new form frmStat
     */
    public frmStat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGraph1 = new javax.swing.JButton();
        btnGraph2 = new javax.swing.JButton();
        btnGraph3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboActions = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnGraph1.setText("graphique 1");
        btnGraph1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph1MouseClicked(evt);
            }
        });

        btnGraph2.setText("graphique 2");
        btnGraph2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph2MouseClicked(evt);
            }
        });

        btnGraph3.setText("graphique 3");
        btnGraph3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph3MouseClicked(evt);
            }
        });

        jLabel1.setText("Le nombre de prescritption par médicament :");

        jLabel2.setText("Répartition des médicaments par famille :");

        jLabel3.setText("Le nombre de prescritption par médicament :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Statistiques : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(cboActions, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGraph1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btnGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnGraph3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnGraph1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGraph2)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnGraph3)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraph1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph1MouseClicked
        // TODO add your handling code here:
         // UNE COURBE
//        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
//        
//        for (Map.Entry valeur : fm.GetDatasGraphique1(cboActions.getSelectedItem().toString()).entrySet())
//        {
//            donnees.setValue(Double.parseDouble(valeur.getValue().toString()), cboActions.getSelectedItem().toString(), valeur.getKey().toString());
//        }
//       
//        JFreeChart chart1 = ChartFactory.createLineChart("le nombre de prescritption par medicament  "+cboActions.getSelectedItem().toString(), "Type individue ", "", donnees);
//        ChartFrame fra = new ChartFrame("Graphique n°1", chart1);
//        fra.pack();
//        fra.setVisible(true);


            ConnexionBDD bdd = new ConnexionBDD();
        FonctionMetier fm = new FonctionMetier();
         DefaultCategoryDataset source1 = new DefaultCategoryDataset();
        
        for(Graph1 g :fm.GetGraph1(cboActions.getSelectedItem().toString()))
        {
            
         source1.setValue( g.getNbPrescription(),cboActions.getSelectedItem().toString(),String.valueOf(g.getLblMedicament()));
        }
        JFreeChart chart2= ChartFactory.createLineChart("le nombre de prescritption par médicament ", "médicament", "nombres", source1);
        ChartFrame fra = new ChartFrame("Graphique n°1", chart2);
        fra.pack();
        fra.setVisible(true);


    }//GEN-LAST:event_btnGraph1MouseClicked

    private void btnGraph2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph2MouseClicked
        // TODO add your handling code here:
        // CAMENBERT
        DefaultPieDataset donnees = new DefaultPieDataset();
        
        for (Map.Entry valeur : fm.GetDatasGraphique2().entrySet())
        {
            donnees.setValue(valeur.getKey().toString(), Integer.parseInt(valeur.getValue().toString()));
        }

        JFreeChart chart1 = ChartFactory.createPieChart(
        "répartition des médicaments par famille",
        donnees,
        true, // légende
        true, // info bulle
        true // url
        );
        ChartFrame frame = new ChartFrame("Graphique n°2", chart1);
        frame.pack();
        frame.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnGraph2MouseClicked

    private void btnGraph3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph3MouseClicked
        // TODO add your handling code here:
        
        // HISTOGRAMME
        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
        
        for (Map.Entry valeur : fm.GetDatasGraphique3().entrySet())
        {
            Double prix = Double.parseDouble(((String[])valeur.getValue())[1].toString());
            String nomTrader = ((String[])valeur.getValue())[0].toString();
            String nomAction = ((String[])valeur.getValue())[2].toString();
            //donnees.setValue(prix,nomAction,nomTrader);
            donnees.setValue(prix,nomTrader,nomAction);
        }
        
        JFreeChart chart1 = ChartFactory.createBarChart(
        "Nombre de médicament par famille",
        "Nom des types",
        "Nombre médicaments",
        donnees,
        PlotOrientation.VERTICAL,
        true, true, false);
        ChartFrame frame = new ChartFrame("Graphique n°3", chart1);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnGraph3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
          // Accès à la BDD
        cnx = new ConnexionBDD();
        fm = new FonctionMetier();
        
        for(String lblIndiv : fm.GetAllIndividusGraph())
        {
            cboActions.addItem(lblIndiv);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraph1;
    private javax.swing.JButton btnGraph2;
    private javax.swing.JButton btnGraph3;
    private javax.swing.JComboBox<String> cboActions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
